export const SET_USER_LIST = "SET_USER_LIST";
export const SET_LOADER = "SET_LOADER";
export const SET_USER_DATA = "SET_USER_DATA";
export const DELETE_USER_DATA = "DELETE_USER_DATA";
export const UPDATE_USER_DATA ="UPDATE_USER_DATA";
